name: kft
base: core20
version: '0.1'
summary: A collection of handy tools for operators of kubeflow environments
description: |
  With kf-tools you have access to a few command line tools to help you operate 
  your kubeflow deployment such as viewing pod logs, checking versions and
  deltas of revision, and scanning for CVEs against pod images.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  kft:
    plugin: python
    source: .